### PR TITLE
Interpolation support with environmental overrides

### PR DESCRIPTION
**Pull request by dpetzold**
If a variables.tf files exists in the directory of the file being parsed; parse it and interpolate its content. "TF_" prefixed environment variables will override the defaults in variables.tf.

### CODE REVIEW

**Comment by virtuald** [comment]
Does HCL support this natively? I don't think interpolation should be a function of the file format.

**Comment by dpetzold** [comment]
Hi Dustin!

Thanks for the response. Your are correct the hashicorp implementation of hcl does not interpolate. However we are using pyhcl to pull configuration information from the terraform hcl files so that information is not duplicated across the project and in order to do that it must interpolate. So if it isn't part of the file format I am not sure where it should live :).

**Comment by virtuald** [comment]
Well, shouldn't that be for the user of the file contents to decide? This is not a terraform library, this is an HCL parsing library. I've never actually used terraform. Perhaps you could create a terraform library that uses pyhcl. :)

Consider it from the perspective of someone implementing a server that parses untrusted HCL content from a user. This would allow that user potential access to the server's environment. I don't think this makes sense in pyhcl.

**Comment by dpetzold** [comment]
Got it. Thanks for the consideration!

**Pull request closed without merging**
