### PR TITLE
Unpin ply version allowing versions until next major release.

### PR DESCRIPTION
**Pull request by moisesguimaraes**
According to discussion in https://github.com/virtuald/pyhcl/pull/38 I'm opening this PR to see if we can move on in the effort to get hvac into OpenStack.

### CODE REVIEW

**Comment by virtuald** [comment]
According to https://travis-ci.org/virtuald/pyhcl/builds/499686034 it appears that 3.8 thru 3.11 work fine. Why should the range be opened up further? PLY doesn't honor semver and has broken compat in the past (though it appears to be in maintenance mode now).

**Comment by moisesguimaraes** [comment]
We need it opened up to comply to OpenStack guidelines, would you like me to open an issue with ply? I think @dabeaz would be willing to honor semver.

**Comment by virtuald** [comment]
What are their guidelines? I'm not familiar with them.

**Comment by moisesguimaraes** [comment]
You can find OpenStack dependency management guidelines here:

https://docs.openstack.org/project-team-guide/dependency-management.html

To my understanding, the global-requirements.txt lists the required packages to run OpenStack services, and the upper-constraints.txt lists the latest version of the required packages and is automatically updated by a bot which would in the future update the version of ply to higher than 3.11 when they release a new version and it would be tested on the CI. But since it is pinpointed to a specific version on your requirements.txt, it would not be "updatable".

I might have missed something or didn't explained the best way cause this is one of my first works adding a new dependency. But I think @prometheanfire could provide more details if needed.

And thanks for putting some time on this, we would really like to switch from https requests to hvac when talking to HashiCorp Vault.

**Comment by prometheanfire** [comment]
that's the basics of it. not much relies on ply right now, but those packages that do would be pinned to the same version pyhcl pins to.

**Comment by virtuald** [comment]
Will fix in master shortly.

**Pull request closed without merging**
