### PR TITLE
Use the latest version of ply instead of a specific version

### PR DESCRIPTION
**Pull request by JamesWrigley**
Now the build shouldn't break every time `ply` gets updated :)

### CODE REVIEW

**Comment by virtuald** [comment]
Whose build? :)

We've had issues with ply making changes that weren't backwards compatible, so I'm reluctant to open it up so widely. I would accept a reasonable range instead.

**Comment by JamesWrigley** [comment]
Ah, I wasn't aware of that. What range would be acceptable?

**Comment by jstoja** [comment]
> Now the build shouldn't break every time ply gets updated :)
It's what would happen by having latest of Ply. Keeping a specific version ensures that everything still works (except if ply changes the code behind the version...).

**Comment by Assassinkin** [comment]
@virtuald  ping

**Comment by virtuald** [comment]
Pong.

**Comment by Assassinkin** [comment]
@virtuald  sorry  i just wanted to know if You are considering updating the version of ply.

**Comment by virtuald** [comment]
I am ok with updating it with a range, I just don't want it to be an unlimited range because of the potential for breakage. I'm open to suggestions.

**Comment by Assassinkin** [comment]
I would suggest to have a range of 2 versions and update that every once in while.

**Comment by prometheanfire** [comment]
I'd use semver, `ply>=3.11,<4` or something

**Comment by prometheanfire** [comment]
that is if you are really concerned about ply breaking (legit reasoning, not hypochondria).

**Comment by prometheanfire** [comment]
this may cause openstack to not allow hvac (vault client) due to locking it down for the rest of openstack (co-installability is a concern).  https://review.openstack.org/639788

**Comment by virtuald** [comment]
Originally I didn't have ply pinned, but they broke something at some point so I pinned it. As I said in the comments above, I'm open to a range.

**Comment by prometheanfire** [comment]
Would `ply>=3.11,<4` work?  If so, should I just submit a PR or do you want to do it?

**Comment by virtuald** [comment]
Given that they've broken a minor version in the past, that seems ill-advised to me. Maybe `>3.7, <=3.11`? Or something similar... though, probably should verify that those versions work.

**Comment by virtuald** [comment]
I pushed a `plytest` branch to build all the different PLY version combinations, so we can see which ones work. https://travis-ci.org/virtuald/pyhcl/builds/499686034

**Comment by virtuald** [comment]
Will fix in master shortly.

**Pull request closed without merging**
